################################################################################
#   Copyright (c) 2021 HCL Technolgies Limited.                                #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
################################################################################
{{- if and .Values.backup.enabled .Values.backup.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "common.fullname.influxdb" . }}-backup
  labels:
    {{- include "common.influxdb.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.backup.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.backup.persistence.size | quote }}
{{- if .Values.backup.persistence.storageClass }}
{{- if (eq "-" .Values.backup.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.backup.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
