################################################################################
#   Copyright (c) 2021 HCL Technolgies Limited.                                #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
################################################################################
{{ if .Values.enterprise.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  name: {{ include "common.fullname.influxdb" . }}-meta
  labels:
    {{- include "common.influxdb.labels" . | nindent 4 }}
    app.kubernets.io/component: meta
spec:
  type: ClusterIP
  clusterIP: None
  # publishNotReadyAddresses is used for service discovery of meta and data nodes by querying the service's SRV record.
  publishNotReadyAddresses: true
  ports:
    - name: meta
      port: {{ include "common.serviceport.influxdb.meta.bind_address" . | default 8091 }}
      targetPort: meta
  selector:
    {{- include "common.influxdb.selectorLabels" . | nindent 4 }}
    app.kubernets.io/component: meta
{{- end }}
