apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.ingressname.appmgr" . }}
spec:
  rules:
  - http:
      paths:
        - pathType: Prefix
          path: {{ include "common.kongpath.ric.appmgr" . }} 
          backend:
            service:
              name: {{ include "common.servicename.appmgr.http" . }}
              port:
                number: {{ include "common.serviceport.appmgr.http" . }}
