################################################################################
#   Copyright (c) 2023 Capgemini Intellectual Property.                        #
################################################################################

dependencies:
  - name: ric-common
    version: ^3.1.0
    repository: "@local"
