apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "common.ingressname.xapp-onboarder" . }}-server
spec:
  rules:
  - http:
      paths:
      - path: {{ include "common.kongpath.ric.xapp-onboarder" . }}
        backend:
          serviceName: {{ include "common.servicename.xapp-onboarder.server" . }}
          servicePort: {{ include "common.serviceport.xapp-onboarder.server" . }}
