#==================================================================================
#   Copyright (c) 2019 AT&T Intellectual Property.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#==================================================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.configmapname.alarmmanager" . }}-alarmmanagercfg
  namespace: {{ include "common.namespace.platform" . }}
data:
  alarmmanagercfg: |-
    {  
      "local": {
        "host": ":8080"
      },
      "logger": {
        "level": 4
      },
      "db": {
        "namespaces": ["sdl", "rnib"]
      },
      "rmr": {
        "protPort": "tcp:4560",
        "maxSize": 1024,
        "numWorkers": 1
      },
      "controls": {
        "promAlertManager": {
          "address": "cpro-alertmanager:80",
          "baseUrl": "api/v2",
          "schemes": "http",
          "alertInterval": 30000
        },
        "maxActiveAlarms": 5000,
        "maxAlarmHistory": 20000,
        "alarmInfoPvFile": "/mnt/pv-ricplt-alarmmanager/alarminfo.json"
      }
    }
